### ISSUE TITLE
Have assembler automatically add a "ret" opcode?

### ISSUE THREAD

**Issue by kevyonan** [assyrianic/C-Virtual-Machine#34]
usually tasm code has a ret at the end of each function...
```asm
%main: {
	mov rsemkath, 5
	call %factorial
	ret
}
```
Would it be better to simply have the assembler automatically add a `ret` opcode to the end of each function?

```asm
%main: {
	mov rsemkath, 5
	call %factorial
}
```

**Comment by Headline** [comment]
imho, i’d prefer if it was left to be explicit.
