### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by rofl0r** [assyrianic/C-Virtual-Machine#36]
interesting project. would you mind adding a license ?

**Comment by kevyonan** [comment]
license is GPL v3. I am in the process of adding it.

**Comment by rofl0r** [comment]
thanks for info. imo the GPL is too restrictive for libraries, but YMMV. (even GLIBC is LGPL for that reason)

**Comment by kevyonan** [comment]
oh, I'm not good with licenses, I just asked around and people told me to just use GPL V3

**Comment by rofl0r** [comment]
that's a good idea, but only if you want nobody else to use your library :)

**Comment by Headline** [comment]
> that's a good idea, but only if you want nobody else to use your library :)

if you only want open-source projects to use your library*

**Comment by kevyonan** [comment]
I should also mention that certain parts of tagha's libc implementation is GPL v3, notably `printf`

**Comment by rofl0r** [comment]
> if you only want open-source projects to use your library*

no, not quite. i do OSS but i would never use a GPL2/3 library, because that forces me to release everything else as GPL too.

> I should also mention that certain parts of tagha's libc implementation is GPL v3, notably printf

that's easy to fix, you can either copy musl libc's which is MIT or this one https://github.com/wm4/libinsanity/blob/master/printf.c

**Comment by Headline** [comment]
> no, not quite. i do OSS but i would never use a GPL2/3 library, because that forces me to release everything else as GPL too.

That's the point though, isn't it, forcing GPL upon the entire project and thus requiring it to be oss

**Comment by rofl0r** [comment]
> That's the point though, isn't it, forcing GPL upon the entire project and thus requiring it to be oss

not really. if i pick another OSS license for my code, it's still OSS, yet not GPL.
i release my libraries under LGPL 2.1, which forces the developer using it to publish any changes/improvement to my library, (and at least object files for his own code, so his users can modify my library and link it again with his object files to create a bugfixed product), but doesn't force a specific license down his throat.
GPL3, OTOH, is a fine choice for **applications** like GCC, or your favorite IDE, etc.

**Comment by kevyonan** [comment]
@rofl0r I have updated the API reference, you're free to change the `printf` implementation for tagha libc. Here's the link to the [code](https://github.com/assyrianic/Tagha-Virtual-Machine/blob/rewrite-oct-2018/tagha_libc/tagha_stdio.c#L93).
Here's a link to the [API reference](https://github.com/assyrianic/Tagha-Virtual-Machine/wiki/Tagha-API-Reference) as well.

I am currently writing more documentation for the internals (VM, ISA) etc. I've already changed the license to **LGPL v3** if it's null and void unless the `printf` code is changed and the GPLv3 code is removed.

**Comment by rofl0r** [comment]
https://softwareengineering.stackexchange.com/questions/189668/lgpl-2-1-vs-lgpl-3-0-advantages-and-disadvantages

quote:
> Myself, I prefer the GPL v2 and LGPL 2.1 licenses because they are simpler [...]

> [...] if you read both the 2-clause BSD license and the GPL v3 (and by extension the LGPL b3) narrowly, these licenses are incompatible because the BSD licenses do not explicitly mention sublicensing unlike the MIT licenses and therefore at least some lawyers like Larry Rosen do not believe such of a license is granted. Therefore you can't just take BSD code and relicense it as GPL v3 without actually adding copyright-worthy changes. Yet everyone agrees the BSD and GPL v3 licenses are compatible. This poses significant problems in interpreting the licenses and line drawing however.

**Comment by assyrianic** [comment]
ok, what license do I use if I want anyone to use tagha in any kind of application so long as I'm credited and any updates/improvements to the VM or the ISA are filed?

**Comment by kevyonan** [comment]
@rofl0r alright, what do you think of the Apache license v2?

**Comment by rofl0r** [comment]
MIT and BSD enforce attribution of the author (license file must accompany binaries and source code), but do not enforce sharing of code modifications. this is generally seen as a very permissive license and favoured by companies and individuals. for example musl libc switched license to MIT from LGPL 2.1, yet many ppl contribute improvements (the reason behind that is that companies do not want to maintain their own set of patches against an ever changing codebase, they prefer having their changes "upstreamed", so they can always just pick the latest version and have their modifications already included).
LGPL 2.1+ is a good choice for libraries, while being copyleft still allowing the user to freely select his own license for his own code. but many companies do generally not use GPL nor LGPL licensed code out of fear that they could be sued.
regarding Apache 2.0, according to https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses it's reasonably permissive, but it is fairly complex and makes it for example impossible to link against GPL 2 code.

**Comment by rofl0r** [comment]
from my PoV as a developer, i jugde the available licenses for *libraries* like this:
good : public domain, WTFPL, MIT, BSD - no brainer, the license text itself is so short a kid can understand it
medium: LGPL 2.1+ (+ means "or later") - slightly restrictrive, relatively complex legalese
bad: GPL2, GPL3, Apache, AGPL, etc - these licenses are either very restrictive (GPL) or so complex you basically need a lawyer to tell you what you can and cannot do.
i can't say much about other licenses as i lack experience with them.

**Comment by kevyonan** [comment]
@rofl0r alright, in terms of what I wish for Tagha, I'm switching to MIT license BUT tagha's stdio implementation will need to be changed or not used. tagha itself doesn't have any form of libc implemented for scripts to use but using the `stdio` implementation will require code to be under GPLv3 unless someone changes the stdio implementation for tagha executables.

**Comment by rofl0r** [comment]
good choice. most ppl will probably only need the stdio impl for testing anyway. but you should probably somehow split it off, for example by putting the license into the subdir it's in and compile it into a separate .a library, which the user can *optionally* link to the code. or just bite the bullet and use the MIT licensed printf impl and rewrite the parts that fetch the variadic arguments.
