### ISSUE TITLE
[HELP] Is there a way to convert/generate TASM directly from C code?

### ISSUE THREAD

**Issue by F70317AA** [assyrianic/C-Virtual-Machine#53]
Hi @assyrianic is there a way to convert/generate .tasm script from our C code directly?

**Comment by kevyonan** [comment]
hey @febryanlicel , in the tagha toolchain folder, there are two header-only API files that will help you with generating Tagha bytecode _and_ creating modules. In the header-only API files are an instruction generator and a Module generator.

If this isn't enough, tell me in more detail what exactly you are doing.

**Comment by F70317AA** [comment]
Thanks for the reply @assyrianic - but I don't think this really answer the question.
So if I understand correctly, I will need to write .tasm script based on my C code (or compiled C code), and then using the assembler to generate Tagha bytecode. Am I right?

I was just looking for a way to automate the process - like directly converting/compiling/mapping the C code to .tasm script, which then can be easily assembled to Tagha bytecode.

**Comment by kevyonan** [comment]
> Thanks for the reply @assyrianic - but I don't think this really answer the question. So if I understand correctly, I will need to write .tasm script based on my C code (or compiled C code), and then using the assembler to generate Tagha bytecode. Am I right?
> 
> I was just looking for a way to automate the process - like directly converting/compiling/mapping the C code to .tasm script, which then can be easily assembled to Tagha bytecode.

Unfortunately I do not have any current tools [at the moment] that compile C [or any other kind of] code to tagha assembly. All of the test tasm scripts were written by hand in order to test and/or profile Tagha.

**Comment by F70317AA** [comment]
@assyrianic Thanks! No worries. Though it will be great to have something like a converter/compiler for this in the future roadmap :)

**Comment by kevyonan** [comment]
> @assyrianic Thanks! No worries. Though it will be great to have something like a converter/compiler for this in the future roadmap :)

can't really do much except make something of a backend but there isn't much because I'm actually redesigning tagha as well as making a dedicated scripting language for it.
